export const showcases = [
  {
    id: "dragon-flight",
    title: "Dragon Flying System",
    category: "Movement / Creature Controller",
    status: "Completed",
    featured: true,
    youtubeUrl: "https://youtu.be/VQQyjB-IkDY",
    videoSrc: "/videos/dragon-flight.mp4",
    posterSrc: "/videos/posters/dragon-flight.jpg",
    visualLabel: "Dragon POV Flight",
    visualSubtext: "Cinematic aerial control showcase",
    summary:
      "A POV showcase of a Roblox dragon flight system focused on cinematic movement, aerial control, and creature-scale game feel.",
    built: [
      "flight controller",
      "camera feel",
      "POV showcase",
      "creature movement",
    ],
    role: "Gameplay programmer / systems designer",
  },
  {
    id: "aot-3dmg",
    title: "Attack on Titan 3DMG System",
    category: "Traversal / Combat Movement",
    status: "Completed",
    featured: true,
    youtubeUrl: "https://youtu.be/Yl26IMocnD8",
    videoSrc: "/videos/aot-3dmg.mp4",
    posterSrc: "/videos/posters/aot-3dmg.jpg",
    visualLabel: "3DMG Movement Leak",
    visualSubtext: "High-speed grappling traversal prototype",
    summary:
      "A proof-of-concept 3D maneuver gear showcase with high-speed traversal, grappling-style movement, and anime-inspired mobility mechanics.",
    built: [
      "3DMG traversal",
      "grapple movement",
      "momentum feel",
      "prototype polish",
    ],
    role: "Gameplay programmer / prototype developer",
  },
  {
    id: "dragon-flight-extended",
    posterSrc: "/videos/posters/dragon-flight-extended.jpg",
    title: "Dragon Flight Extended Showcase",
    category: "Movement / Creature Controller",
    status: "Completed",
    featured: false,
    videoSrc: "/videos/dragon-flight%202.mp4",
    visualLabel: "Dragon Flight Expansion",
    visualSubtext: "Additional creature movement and flight showcase",
    summary:
      "An additional dragon flight showcase focused on creature-scale movement, aerial control, and cinematic gameplay presentation.",
    built: [
      "flight controller",
      "creature movement",
      "camera feel",
      "showcase polish",
    ],
    role: "Gameplay programmer / systems designer",
  },
  {
    id: "fps-system-wip",
    posterSrc: "/videos/posters/fps-system-wip.jpg",
    title: "FPS System Prototype",
    category: "FPS / Combat Systems",
    status: "Work in progress",
    featured: false,
    videoSrc: "/videos/Roblox%20Studio%202026.06.08%20-%2019.51.23.18.mp4",
    visualLabel: "FPS System WIP",
    visualSubtext: "Early first-person combat prototype",
    summary:
      "A heavily work-in-progress Roblox FPS system prototype exploring first-person weapon handling, combat feel, and the foundation for a larger shooter system.",
    built: [
      "FPS controller",
      "weapon handling",
      "combat prototype",
      "WIP systems",
    ],
    role: "Gameplay programmer / prototype developer",
  },
  {
    id: "game-of-thrones-roleplay",
    posterSrc: "/videos/posters/game-of-thrones-roleplay.jpg",
    title: "Game of Thrones Roleplay Game",
    category: "Roleplay / World Systems",
    status: "Completed",
    featured: false,
    videoSrc: "/videos/game%20of%20thrones%20roleplay%20game.mp4",
    visualLabel: "Roleplay Systems",
    visualSubtext: "Fantasy roleplay gameplay concept",
    summary:
      "A fantasy roleplay showcase exploring Roblox gameplay presentation, world interaction, and roleplay-oriented systems.",
    built: [
      "roleplay systems",
      "world interaction",
      "prototype scene",
      "gameplay presentation",
    ],
    role: "Gameplay programmer / prototype developer",
  },
  {
    id: "tokyo-ghoul-concept",
    posterSrc: "/videos/posters/tokyo-ghoul-concept.jpg",
    title: "Tokyo Ghoul Concept",
    category: "Combat / Anime Systems",
    status: "Completed",
    featured: false,
    videoSrc: "/videos/Tokyo%20Ghoul%20concept.mp4",
    visualLabel: "Tokyo Ghoul Concept",
    visualSubtext: "Anime-inspired combat prototype",
    summary:
      "An anime-inspired Roblox combat concept focused on ability presentation, movement feel, and prototype gameplay direction.",
    built: [
      "anime combat",
      "ability feel",
      "prototype systems",
      "visual direction",
    ],
    role: "Gameplay programmer / prototype developer",
  },
  {
    id: "naruto-game-concept",
    posterSrc: "/videos/posters/naruto-game-concept.jpg",
    title: "Naruto Game Concept",
    category: "Combat / Anime Systems",
    status: "Proof of concept",
    featured: false,
    videoSrc: "/videos/Naruto%20game%20concept.mp4",
    visualLabel: "Naruto Systems Concept",
    visualSubtext: "Anime-inspired combat and movement prototype",
    summary:
      "A Naruto-inspired Roblox concept exploring anime combat presentation, movement feel, and ability-driven gameplay systems.",
    built: [
      "anime combat",
      "ability systems",
      "movement feel",
      "prototype polish",
    ],
    role: "Gameplay programmer / prototype developer",
  },
  {
    id: "naruto-game-concept-2",
    posterSrc: "/videos/posters/naruto-game-concept-2.jpg",
    title: "Naruto Game Concept 2",
    category: "Combat / Anime Systems",
    status: "Proof of concept",
    featured: false,
    videoSrc: "/videos/Naruto%20game%20concept%202.mp4",
    visualLabel: "Naruto Systems Concept",
    visualSubtext: "Additional anime-inspired combat showcase",
    summary:
      "A second Naruto-inspired Roblox showcase exploring ability systems, combat presentation, movement feel, and prototype polish.",
    built: [
      "anime combat",
      "ability systems",
      "movement feel",
      "combat showcase",
    ],
    role: "Gameplay programmer / prototype developer",
  },
  {
    id: "starwars",
    title: "Star Wars Showcase",
    category: "Combat / Sci-Fi Systems",
    status: "Proof of concept",
    featured: false,
    youtubeUrl: "https://youtu.be/EpNrl1s5SZg",
    videoSrc: "/videos/starwars-showcase.mp4",
    posterSrc: "/videos/posters/starwars-showcase.jpg",
    visualLabel: "Star Wars Systems",
    visualSubtext: "Sci-fi combat and presentation showcase",
    summary:
      "A sci-fi Roblox showcase exploring Star Wars-inspired gameplay, visuals, and combat presentation.",
    built: [
      "sci-fi combat",
      "visual direction",
      "prototype systems",
      "showcase scene",
    ],
    role: "Gameplay programmer / Roblox developer",
  },
];
